import { useEffect, useMemo, useRef, useState } from 'react'
import { Capacitor } from '@capacitor/core'
import { Directory, Encoding, Filesystem } from '@capacitor/filesystem'
import { Share } from '@capacitor/share'
import { ArrowLeft, ArrowRight, Beaker, BookOpen, Calculator as CalcIcon, Camera, Check, ChevronRight, Download, FlaskConical, Layers3, MoreHorizontal, Palette, Plus, RotateCcw, Search, Upload, X } from 'lucide-react'
import { calculateRecipe, createCalculation, validateCalculation } from './domain'
import { coneDB } from './db'
import type { Calculation, ConeBackup, FiringTest, Ingredient, IngredientKind, Material } from './types'

type Tab = '계산' | '기록' | '색상' | '내 유약'
type Screen = 'main' | 'result' | 'new-record' | 'detail'
const photos = [
  '/glaze-sea.svg', '/glaze-cloud.svg', '/glaze-moss.svg',
]
const makeIngredient = (name: string, amount: number, kind: IngredientKind): Ingredient => ({ id: Date.now() + Math.random(), name, amount, kind, snapshot: { genericName: name, verification: '사용자 입력' } })
const initial = [makeIngredient('장석', 40, 'base'), makeIngredient('석회석', 20, 'base'), makeIngredient('규석', 40, 'base'), makeIngredient('산화아연', 2, 'additive')]
const builtInMaterials: Material[] = [
  { id: 'feldspar', genericName: '장석', formula: 'K₂O·Al₂O₃·6SiO₂', verification: '대표값', kind: 'base', custom: false },
  { id: 'silica', genericName: '규석', formula: 'SiO₂', verification: '확인됨', kind: 'base', custom: false },
  { id: 'limestone', genericName: '석회석', formula: 'CaCO₃', verification: '확인됨', kind: 'base', custom: false },
  { id: 'kaolin', genericName: '카올린', formula: 'Al₂O₃·2SiO₂·2H₂O', verification: '대표값', kind: 'base', custom: false },
  { id: 'dolomite', genericName: '백운석', formula: 'CaMg(CO₃)₂', verification: '대표값', kind: 'base', custom: false },
  { id: 'zinc-oxide', genericName: '산화아연', formula: 'ZnO', verification: '확인됨', kind: 'additive', custom: false },
  { id: 'bentonite', genericName: '벤토나이트', verification: '대표값', kind: 'additive', custom: false },
  { id: 'cobalt', genericName: '산화코발트', formula: 'CoO', verification: '대표값', kind: 'additive', custom: false },
  { id: 'copper', genericName: '산화동', formula: 'CuO', verification: '대표값', kind: 'additive', custom: false },
  { id: 'iron', genericName: '산화철', formula: 'Fe₂O₃', verification: '대표값', kind: 'additive', custom: false },
]
const fileData = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file) })

function Mascot() { return <img src="/cone-mascot.png" alt="CONE 8" /> }
function Header({ title, back, action }: { title?: string; back?: () => void; action?: () => void }) {
  return <header className="app-header"><span>{back && <button onClick={back}><ArrowLeft /></button>}</span><div className="wordmark"><Mascot /><b>CONE</b></div><span className="right">{action && <button onClick={action}><MoreHorizontal /></button>}</span>{title && <h1>{title}</h1>}</header>
}

export default function App() {
  const [tab, setTab] = useState<Tab>('계산'); const [screen, setScreen] = useState<Screen>('main')
  const [ingredients, setIngredients] = useState<Ingredient[]>(initial); const [target, setTarget] = useState(520)
  const [history, setHistory] = useState<Calculation[]>([]); const [tests, setTests] = useState<FiringTest[]>([])
  const [materials, setMaterials] = useState<Material[]>([]); const [materialTarget, setMaterialTarget] = useState<{ id: number; kind: IngredientKind } | null>(null)
  const [selected, setSelected] = useState<Calculation | null>(null); const [settings, setSettings] = useState(false); const [toast, setToast] = useState('')
  const importRef = useRef<HTMLInputElement>(null)
  const result = useMemo(() => calculateRecipe(target, ingredients), [target, ingredients]); const error = validateCalculation(target, ingredients)
  const refresh = async () => { const [saved, firing, storedMaterials] = await Promise.all([coneDB.calculations.all(), coneDB.firingTests.all(), coneDB.materials.all()]); setHistory(saved.sort((a, b) => b.createdAt.localeCompare(a.createdAt))); setTests(firing.sort((a, b) => b.date.localeCompare(a.date))); setMaterials(storedMaterials) }
  useEffect(() => {
    void Promise.all([coneDB.calculations.all(), coneDB.firingTests.all(), coneDB.materials.all()])
      .then(async ([saved, firing, storedMaterials]) => {
        const merged = [...storedMaterials]
        for (const material of builtInMaterials) if (!merged.some((item) => item.id === material.id)) { await coneDB.materials.put(material); merged.push(material) }
        setHistory(saved.sort((a, b) => b.createdAt.localeCompare(a.createdAt)))
        setTests(firing.sort((a, b) => b.date.localeCompare(a.date)))
        setMaterials(merged)
      })
      .catch(() => setToast('기기 저장소를 열지 못했습니다'))
  }, [])
  function tell(text: string) { setToast(text); window.setTimeout(() => setToast(''), 2300) }
  function navigate(next: Tab) { setTab(next); setScreen('main'); setSelected(null); window.scrollTo({ top: 0, behavior: 'instant' }) }
  function update(id: number, field: 'name' | 'amount', value: string) { setIngredients((rows) => rows.map((row) => row.id === id ? { ...row, [field]: field === 'amount' ? Math.max(0, Number(value)) : value } : row)) }
  async function calculate() { if (error) return tell(error); const record = createCalculation(target, ingredients); record.title = '나의 유약'; record.saved = true; await coneDB.calculations.put(record); setHistory((rows) => [record, ...rows]); setSelected(record); setScreen('result') }
  function reuse(item: Calculation) { setIngredients(structuredClone(item.ingredients)); setTarget(item.target); setTab('계산'); setScreen('main'); tell('배합을 계산기로 불러왔습니다') }
  async function exportData() { const backup = await coneDB.export(); const name = `cone-backup-${new Date().toISOString().slice(0, 10)}.json`; const data = JSON.stringify(backup, null, 2); if (Capacitor.isNativePlatform()) { const file = await Filesystem.writeFile({ path: name, data, directory: Directory.Cache, encoding: Encoding.UTF8 }); await Share.share({ title: 'CONE 백업', url: file.uri }) } else { const url = URL.createObjectURL(new Blob([data], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) } tell('백업 파일을 만들었습니다') }
  async function importData(file?: File) { if (!file) return; await coneDB.import(JSON.parse(await file.text()) as ConeBackup); await refresh(); setSettings(false); tell('백업을 복원했습니다') }
  return <div className="ios-app"><div className="ios-frame"><main>
    {tab === '계산' && screen === 'main' && <Calculator ingredients={ingredients} setIngredients={setIngredients} target={target} result={result} error={error} setTarget={setTarget} update={update} calculate={calculate} settings={() => setSettings(true)} chooseMaterial={(id, kind) => setMaterialTarget({ id, kind })} />}
    {tab === '계산' && screen === 'result' && <Result target={selected?.target ?? target} result={selected ? calculateRecipe(selected.target, selected.ingredients) : result} back={() => setScreen('main')} />}
    {tab === '기록' && screen === 'main' && <Journal tests={tests} add={() => setScreen('new-record')} />}
    {tab === '기록' && screen === 'new-record' && <NewRecord recipes={history} back={() => setScreen('main')} save={async (test) => { await coneDB.firingTests.put(test); setTests((rows) => [test, ...rows]); setScreen('main'); tell('소성 기록을 저장했습니다') }} />}
    {tab === '색상' && <Colors tell={tell} />}
    {tab === '내 유약' && screen === 'main' && <Gallery history={history} open={(item) => { setSelected(item); setScreen('detail') }} />}
    {tab === '내 유약' && screen === 'detail' && selected && <Detail item={selected} tests={tests.filter((t) => t.recipeId === selected.id)} back={() => setScreen('main')} reuse={() => reuse(selected)} />}
  </main><Nav tab={tab} navigate={navigate} /></div>
  {settings && <div className="backdrop" onClick={() => setSettings(false)}><section className="sheet" onClick={(e) => e.stopPropagation()}><div className="sheet-head"><div><small>LOCAL DATA</small><h2>내 데이터 관리</h2></div><button onClick={() => setSettings(false)}><X /></button></div><p>레시피와 사진은 계정이 아니라 이 기기에 저장됩니다. 기기를 바꾸기 전 백업 파일을 만들어 주세요.</p><button className="outline" onClick={exportData}><Download /> 전체 백업 내보내기</button><button className="outline" onClick={() => importRef.current?.click()}><Upload /> 백업 파일 복원하기</button></section></div>}
  {materialTarget && <MaterialPicker kind={materialTarget.kind} materials={materials} close={() => setMaterialTarget(null)} select={async (material) => { const used = { ...material, lastUsedAt: new Date().toISOString(), useCount: (material.useCount ?? 0) + 1 }; await coneDB.materials.put(used); setMaterials((rows) => rows.map((row) => row.id === used.id ? used : row)); setIngredients((rows) => rows.map((row) => row.id === materialTarget.id ? { ...row, name: material.productName ?? material.genericName, snapshot: { materialId: material.id, genericName: material.genericName, productName: material.productName, manufacturer: material.manufacturer, supplier: material.supplier, region: material.region, formula: material.formula, source: material.source, version: material.version, verification: material.verification } } : row)); setMaterialTarget(null) }} create={async (material) => { await coneDB.materials.put(material); setMaterials((rows) => [material, ...rows]); setIngredients((rows) => rows.map((row) => row.id === materialTarget.id ? { ...row, name: material.genericName, snapshot: { materialId: material.id, genericName: material.genericName, formula: material.formula, verification: '사용자 입력' } } : row)); setMaterialTarget(null); tell('새 재료를 기기에 저장했습니다') }} />}
  <input ref={importRef} hidden type="file" accept=".json" onChange={(e) => void importData(e.target.files?.[0])} />{toast && <div className="toast"><Check />{toast}</div>}</div>
}

type CalculatorProps = { ingredients: Ingredient[]; setIngredients: React.Dispatch<React.SetStateAction<Ingredient[]>>; target: number; result: ReturnType<typeof calculateRecipe>; error: string | null; setTarget: (n: number) => void; update: (id: number, field: 'name' | 'amount', value: string) => void; calculate: () => void; settings: () => void; chooseMaterial: (id: number, kind: IngredientKind) => void }
function Calculator(p: CalculatorProps) {
  return <div className="page"><Header action={p.settings} /><section className="heading"><small>GLAZE RECIPE</small><h1>유약 계산</h1><p>기본 재료와 첨가제를 입력하면 원하는 양으로 정확하게 환산해드려요.</p></section><section className="card recipe"><span>레시피 이름</span><input defaultValue="나의 유약" /><ChevronRight /></section>
    {(['base', 'additive'] as IngredientKind[]).map((kind) => <section className="card materials" key={kind}><div className="card-head"><i className={kind}><Layers3 /></i><div><h2>{kind === 'base' ? '기본 재료' : '추가 재료'}</h2><p>{kind === 'base' ? '전체 배합의 기준이 되는 재료' : '기본 재료 총량을 기준으로 계산'}</p></div><b>{kind === 'base' ? 'g' : '%'}</b></div>{p.ingredients.filter((row) => row.kind === kind).map((row) => <div className="material" key={row.id}><button className="material-select" onClick={() => p.chooseMaterial(row.id, kind)}><span>{row.name}</span><ChevronRight /></button><label><input aria-label={`${row.name} 양`} type="number" value={row.amount} onChange={(e) => p.update(row.id, 'amount', e.target.value)} /><span>{kind === 'base' ? 'g' : '%'}</span></label><button onClick={() => p.setIngredients((rows) => rows.filter((r) => r.id !== row.id))}><X /></button></div>)}<button className="add" onClick={() => { const row = makeIngredient(kind === 'base' ? '재료 선택' : '첨가제 선택', kind === 'base' ? 10 : 1, kind); p.setIngredients((rows) => [...rows, row]); p.chooseMaterial(row.id, kind) }}><Plus /> 재료 추가</button></section>)}
    <section className="card target"><i><CalcIcon /></i><div><span>목표 총량</span><b>{p.result.originalTotal.toFixed(0)} g →</b></div><label><input type="number" value={p.target} onChange={(e) => p.setTarget(Number(e.target.value))} /><span>g</span></label></section>{p.error && <p className="error">{p.error}</p>}<button className="cta" disabled={!!p.error} onClick={p.calculate}>이 배합으로 환산하기 <ArrowRight /></button></div>
}

function Result({ target, result, back }: { target: number; result: ReturnType<typeof calculateRecipe>; back: () => void }) {
  const tones = ['blue', 'yellow', 'green', 'pink']
  return <div className="page"><Header back={back} /><section className="heading"><small>CALCULATION RESULT</small><h1>환산 결과</h1><p>입력한 비율을 유지하여 {target.toLocaleString()}g으로 계산했어요.</p></section><section className="card summary"><div><span>목표 총량</span><b>{target.toLocaleString()}<small>g</small></b></div><em><Check /> 계산 완료</em></section><section className="card results">{result.rows.map((row, i) => <div key={row.id}><i className={tones[i % 4]}></i><span><b>{row.name}</b><small>{row.kind === 'base' ? `${row.amount}g 입력` : `${row.amount}% 첨가`}</small></span><strong>{row.scaledGrams.toFixed(2)}<small>g</small></strong></div>)}</section><section className="card ratio"><div className="donut"><span>총 중량<b>{target}<small>g</small></b></span></div><div>{result.rows.slice(0, 4).map((row, i) => <p key={row.id}><i className={tones[i]}></i><span>{row.name}</span><b>{Math.round(row.scaledGrams / target * 100)}%</b></p>)}</div></section><button className="cta coral"><BookOpen /> 내 유약으로 저장</button><button className="recent" onClick={back}><RotateCcw /> 수치를 수정해서 다시 계산 <ChevronRight /></button></div>
}

function Journal({ tests, add }: { tests: FiringTest[]; add: () => void }) { return <div className="page"><Header /><section className="heading action"><div><small>FIRING JOURNAL</small><h1>소성 기록</h1><p>테스트 결과를 사진과 함께 남겨보세요.</p></div><button onClick={add}><Plus /></button></section>{tests.length ? <div className="journals">{tests.map((test, i) => <article key={test.id}><img src={test.photos[0]?.data || photos[i % photos.length]} alt="" /><div><small>{new Date(test.date).toLocaleDateString('ko-KR')}</small><h2>{test.name}</h2><p>{test.peakTemperature}°C · {test.atmosphere}소성 · {test.clay}</p><Swatches /></div><ChevronRight /></article>)}</div> : <Empty add={add} />}<button className="floating" onClick={add}><Plus /> 새 소성 기록</button></div> }
function Empty({ add }: { add: () => void }) { return <section className="empty"><i><Camera /></i><h2>첫 소성 결과를 기록해보세요</h2><p>사진, 온도, 분위기와 메모를 함께 저장하면<br />다음 배합에서 바로 참고할 수 있어요.</p><button onClick={add}><Camera /> 기록 시작하기</button></section> }

function NewRecord({ recipes, back, save }: { recipes: Calculation[]; back: () => void; save: (t: FiringTest) => void }) {
  const [name, setName] = useState('첫 번째 테스트'); const [recipeId, setRecipeId] = useState(recipes[0]?.id ?? ''); const [temperature, setTemperature] = useState(1250); const [atmosphere, setAtmosphere] = useState<FiringTest['atmosphere']>('산화'); const [clay, setClay] = useState('백자토'); const [notes, setNotes] = useState(''); const [photo, setPhoto] = useState<File | null>(null)
  const preview = photo ? URL.createObjectURL(photo) : ''
  return <div className="page"><Header title="새 소성 기록" back={back} /><label className="photo-input">{preview ? <img src={preview} alt="" /> : <><Camera /><b>결과 사진 추가</b><span>정면 사진을 밝은 곳에서 촬영해 주세요</span></>}<input type="file" accept="image/*" onChange={(e) => setPhoto(e.target.files?.[0] ?? null)} /></label><section className="card form"><label><span>기록 이름</span><input value={name} onChange={(e) => setName(e.target.value)} /></label><label><span>연결할 유약</span><select value={recipeId} onChange={(e) => setRecipeId(e.target.value)}><option value="">선택 안 함</option>{recipes.map((r) => <option value={r.id} key={r.id}>{r.title}</option>)}</select></label><label><span>최고 온도</span><input type="number" value={temperature} onChange={(e) => setTemperature(Number(e.target.value))} /></label><label><span>소성 분위기</span><select value={atmosphere} onChange={(e) => setAtmosphere(e.target.value as FiringTest['atmosphere'])}><option>산화</option><option>환원</option><option>기타</option></select></label><label><span>소지</span><input value={clay} onChange={(e) => setClay(e.target.value)} /></label><label><span>메모</span><textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></label></section><button className="cta" onClick={async () => save({ id: crypto.randomUUID(), recipeId, name, date: new Date().toISOString(), clay, thickness: '', peakTemperature: temperature, atmosphere, kiln: '', durationHours: 0, notes, photos: photo ? [{ id: crypto.randomUUID(), name: photo.name, type: photo.type, size: photo.size, data: await fileData(photo) }] : [] })}>기록 저장하기</button></div>
}

function Colors({ tell }: { tell: (s: string) => void }) { const [photo, setPhoto] = useState(''); return <div className="page"><Header /><section className="heading"><small>COLOR LIBRARY</small><h1>사진에서 색 추출</h1><p>소성 결과 사진에서 마음에 드는 색을 골라 저장해보세요.</p></section><label className={`color-photo ${photo ? 'filled' : ''}`}>{photo ? <><img src={photo} alt="" /><i className="pick one"></i><i className="pick two"></i><i className="pick three"></i></> : <><Palette /><b>사진을 선택해 주세요</b><span>도자기 표면이 잘 보이는 사진이 좋아요</span></>}<input type="file" accept="image/*" onChange={async (e) => { const file = e.target.files?.[0]; if (file) setPhoto(await fileData(file)) }} /></label><section className="card palette"><div className="card-head"><i className="base"><Palette /></i><div><h2>대표 색상</h2><p>사진에서 추출된 컬러 팔레트</p></div></div><div><i style={{ background: '#6d9996' }}></i><i style={{ background: '#a8c8c4' }}></i><i style={{ background: '#e6e4d8' }}></i><i style={{ background: '#74695d' }}></i></div></section><button className="cta coral" disabled={!photo} onClick={() => tell('대표 색상을 저장했습니다')}><BookOpen /> 이 색을 기록에 저장</button></div> }

function Gallery({ history, open }: { history: Calculation[]; open: (c: Calculation) => void }) { const [query, setQuery] = useState(''); const rows = history.filter((r) => `${r.title}${r.ingredients.map((i) => i.name).join('')}`.includes(query)); return <div className="page"><Header /><section className="heading"><small>MY GLAZES</small><h1>나의 유약</h1><p>계산하고 테스트한 유약을 한눈에 모아보세요.</p></section><div className="search"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="유약 이름이나 재료 검색" /></div><div className="pills"><button>전체</button><button>즐겨찾기</button><button>최근 기록</button></div>{rows.length ? <div className="gallery">{rows.map((row, i) => <button key={row.id} onClick={() => open(row)}><div><img src={photos[i % photos.length]} alt="" /><em>{row.target}g</em></div><Swatches /><h2>{row.title}</h2><p>{row.ingredients.slice(0, 3).map((x) => x.name).join(' · ')}</p></button>)}</div> : <section className="empty"><i><FlaskConical /></i><h2>저장된 유약이 없어요</h2><p>계산 결과를 저장하면 이곳에서<br />배합과 소성 기록을 함께 관리할 수 있어요.</p></section>}</div> }
function Swatches() { return <span className="swatches"><i></i><i></i><i></i></span> }
function Detail({ item, tests, back, reuse }: { item: Calculation; tests: FiringTest[]; back: () => void; reuse: () => void }) { return <div className="page"><Header back={back} /><div className="hero-photo"><img src={tests[0]?.photos[0]?.data || photos[0]} alt="" /></div><section className="detail-title"><Swatches /><h1>{item.title}</h1><p>{tests[0] ? `${tests[0].peakTemperature}°C · ${tests[0].atmosphere}소성` : '아직 소성 기록이 없습니다'}</p></section><section className="card details"><h2><Beaker /> 배합 비율</h2>{item.ingredients.map((row) => <p key={row.id}><span>{row.name}</span><b>{row.amount}{row.kind === 'base' ? ' g' : '%'}</b></p>)}</section><section className="card details"><h2><FlaskConical /> 화학식</h2><div className="chem"><span>SiO₂<b>0.64</b></span><span>Al₂O₃<b>0.18</b></span><span>CaO<b>0.12</b></span></div></section><button className="cta" onClick={reuse}><RotateCcw /> 이 배합으로 다시 계산</button></div> }

function MaterialPicker({ kind, materials, close, select, create }: { kind: IngredientKind; materials: Material[]; close: () => void; select: (material: Material) => void; create: (material: Material) => void }) {
  const [query, setQuery] = useState(''); const [creating, setCreating] = useState(false); const [formula, setFormula] = useState('')
  const filtered = materials.filter((material) => material.kind === kind && `${material.genericName} ${material.productName ?? ''} ${material.formula ?? ''}`.toLocaleLowerCase('ko').includes(query.trim().toLocaleLowerCase('ko'))).sort((a, b) => (b.lastUsedAt ?? '').localeCompare(a.lastUsedAt ?? '') || (b.useCount ?? 0) - (a.useCount ?? 0) || a.genericName.localeCompare(b.genericName, 'ko'))
  return <div className="backdrop" onClick={close}><section className="sheet material-sheet" onClick={(e) => e.stopPropagation()}><div className="sheet-grabber"></div><div className="sheet-head"><div><small>ON-DEVICE MATERIALS</small><h2>{kind === 'base' ? '기본 재료 선택' : '추가 재료 선택'}</h2></div><button onClick={close}><X /></button></div><div className="material-search"><Search /><input autoFocus value={query} onChange={(e) => { setQuery(e.target.value); setCreating(false) }} placeholder="재료명 또는 화학식 검색" /></div><div className="material-scroll">{filtered.map((material) => <button className="material-option" key={material.id} onClick={() => select(material)}><i>{material.genericName.slice(0, 1)}</i><span><b>{material.productName ?? material.genericName}</b><small>{material.formula || (material.custom ? '내가 추가한 재료' : '기본 제공 재료')}{material.lastUsedAt ? ' · 최근 사용' : ''}</small></span><ChevronRight /></button>)}{filtered.length === 0 && !creating && <div className="no-material"><p>“{query}” 재료가 없습니다.</p><button onClick={() => setCreating(true)}><Plus /> 새 재료로 추가</button></div>}</div>{creating && <div className="new-material"><label>재료명<input value={query} onChange={(e) => setQuery(e.target.value)} /></label><label>화학식 · 메모<input value={formula} onChange={(e) => setFormula(e.target.value)} placeholder="선택 입력" /></label><button className="cta" disabled={!query.trim()} onClick={() => create({ id: crypto.randomUUID(), genericName: query.trim(), formula: formula.trim(), verification: '사용자 입력', kind, custom: true, lastUsedAt: new Date().toISOString(), useCount: 1 })}>이 기기에 재료 저장</button></div>}<button className="new-material-trigger" onClick={() => setCreating(true)}><Plus /> 목록에 없는 재료 추가</button><p className="device-note">이 목록과 사용 기록은 이 기기의 로컬 DB에만 저장됩니다.</p></section></div>
}

function Nav({ tab, navigate }: { tab: Tab; navigate: (t: Tab) => void }) { const items: [Tab, typeof CalcIcon][] = [['계산', CalcIcon], ['기록', BookOpen], ['색상', Palette], ['내 유약', FlaskConical]]; return <nav>{items.map(([name, Icon]) => <button className={tab === name ? 'active' : ''} key={name} onClick={() => navigate(name)}><i><Icon /></i>{name}</button>)}</nav> }
